# Site settings
title: Manas Documentation
description: Documentation for the Manas Multi-Agent System Framework
baseurl: ""
url: "https://manas.koley.in"

# Theme settings
theme: null
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  api:
    output: true
    permalink: /api/:path/
  examples:
    output: true
    permalink: /examples/:path/

defaults:
  - scope:
      path: ""
      type: "api"
    values:
      layout: "reference"
      nav_section: "api"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "tutorial"
      nav_section: "examples"
  - scope:
      path: ""
    values:
      layout: "default"

# Material Design settings
material_theme:
  primary: "#6750A4"
  on-primary: "#FFFFFF"
  primary-container: "#EADDFF"
  on-primary-container: "#21005E"
  secondary: "#625B71"
  on-secondary: "#FFFFFF"
  surface: "#FFFBFE"
  on-surface: "#1C1B1F"
  background: "#FFFBFE"
  on-background: "#1C1B1F"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - package.json
  - package-lock.json

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

# Navigation
nav_sections:
  - Getting Started
  - Core Concepts
  - API Reference
  - Examples
  - FAQ