title: Manas
description: A framework for building LLM-powered applications with intelligent agents, task decomposition, and RAG
url: https://arkokoley.github.io
baseurl: /manas

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme settings
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

# Just the Docs settings
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Enable or disable heading anchors
heading_anchors: true

# Sort order for navigation links
nav_sort: case_sensitive

# Auxiliary links
aux_links:
  "Manas on GitHub":
    - "https://github.com/arkokoley/manas"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; Manas Contributors. Distributed under an MIT license."

# Collections
collections:
  api:
    output: true
    permalink: /api/:path/
  examples:
    output: true
    permalink: /examples/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_api"
    values:
      layout: default
      parent: "API Reference"
  - scope:
      path: "_examples"
    values:
      layout: default
      parent: "Examples"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/